"""Catalog of supported financial metrics (XBRL tags, units, keywords)."""
from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class Metric:
    key: str
    label: str
    tags: Tuple[str, ...]  # tried in priority order
    kind: str  # "duration" (income/cash-flow statement) or "instant" (balance sheet)
    unit: str  # unit stored in XBRL facts (EPS is reported as "USD")
    synonyms: Tuple[str, ...]
    mdna_keywords: Tuple[str, ...]
    per_share: bool = False

    @property
    def display_unit(self) -> str:
        return "USD/shares" if self.per_share else self.unit


METRICS: Dict[str, Metric] = {
    m.key: m
    for m in (
        Metric("revenue", "Revenue",
               ("RevenueFromContractWithCustomerExcludingAssessedTax", "Revenues", "SalesRevenueNet",
                "RevenueFromContractWithCustomerIncludingAssessedTax", "SalesRevenueGoodsNet"),
               "duration", "USD", ("revenue", "revenues", "net sales", "sales", "top line", "turnover"),
               ("net sales", "total net sales", "revenue")),
        Metric("net_income", "Net income", ("NetIncomeLoss", "ProfitLoss"), "duration", "USD",
               ("net income", "net profit", "profit", "earnings", "net loss", "bottom line"),
               ("net income", "net loss")),
        Metric("gross_profit", "Gross profit", ("GrossProfit",), "duration", "USD",
               ("gross profit", "gross margin"), ("gross margin", "gross profit")),
        Metric("operating_income", "Operating income", ("OperatingIncomeLoss",), "duration", "USD",
               ("operating income", "operating profit", "operating loss", "ebit"), ("operating income", "operating margin")),
        Metric("rnd", "Research and development expense", ("ResearchAndDevelopmentExpense",), "duration", "USD",
               ("research and development", "r&d", "rnd", "research"), ("research and development",)),
        Metric("eps_diluted", "Diluted EPS", ("EarningsPerShareDiluted",), "duration", "USD",
               ("eps", "earnings per share", "diluted eps", "per share"), ("per share", "earnings per share"), per_share=True),
        Metric("operating_cash_flow", "Operating cash flow", ("NetCashProvidedByUsedInOperatingActivities",),
               "duration", "USD", ("operating cash flow", "cash from operations", "cash flow", "ocf"),
               ("cash generated by operating", "operating activities", "cash flow")),
        Metric("total_assets", "Total assets", ("Assets",), "instant", "USD", ("total assets", "assets"),
               ("total assets", "assets")),
        Metric("total_liabilities", "Total liabilities", ("Liabilities",), "instant", "USD",
               ("total liabilities", "liabilities", "debt"), ("liabilities",)),
    )
}
